import { mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname } from "node:path";
import {
  BitgetRestClient,
  buildTools,
  loadConfig,
  safeInvoke,
  type ToolContext,
  type ToolSpec,
} from "@bitget-ai/bitget-agent-sdk";

const ACTIONS = [
  "tickers",
  "orderbook",
  "candles",
  "candlesHistory",
  "instruments",
  "fundingRate",
  "fundingRateHistory",
  "openInterest",
] as const;

const OUT = "docs/dev/market-schemas.md";

async function dump(
  discover: ToolSpec,
  ctx: ToolContext,
  args: Record<string, unknown>,
): Promise<string> {
  const res = await safeInvoke(discover, args, ctx);
  if (!res.ok) {
    return JSON.stringify(res, null, 2);
  }
  return JSON.stringify(res.data, null, 2);
}

async function main(): Promise<void> {
  const config = loadConfig({ modules: "market", readOnly: true });
  const client = new BitgetRestClient(config);
  const ctx: ToolContext = { config, client };
  const tools = buildTools(config);
  const discover = tools.find((t) => t.name === "discover");
  if (!discover) {
    throw new Error("the SDK did not build a discover tool");
  }

  const parts: string[] = [];
  parts.push("# Bitget market tool schemas, copied from the SDK");
  parts.push("");
  parts.push(
    "Generated by `npm run discover` against @bitget-ai/bitget-agent-sdk. Every parameter",
    "name used in src/bitget comes from this file, not from a guess. Regenerate after an",
    "SDK upgrade and re-read the diff before changing any caller.",
  );
  parts.push("");
  parts.push(`SDK version: ${readSdkVersion()}`);
  parts.push(`Generated: ${new Date().toISOString()}`);
  parts.push("");
  parts.push("## tool: market");
  parts.push("");
  parts.push("```json");
  parts.push(await dump(discover, ctx, { tool: "market" }));
  parts.push("```");
  parts.push("");

  for (const action of ACTIONS) {
    parts.push(`## market action: ${action}`);
    parts.push("");
    parts.push("```json");
    parts.push(await dump(discover, ctx, { tool: "market", action }));
    parts.push("```");
    parts.push("");
  }

  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, parts.join("\n"), { encoding: "utf8" });
  console.log(`wrote ${OUT} with the market tool plus ${ACTIONS.length} action schemas`);
}

function readSdkVersion(): string {
  const pkg = createRequire(import.meta.url)("@bitget-ai/bitget-agent-sdk/package.json") as {
    version: string;
  };
  return pkg.version;
}

await main();
